# Generated by Django 4.2.1 on 2023-07-10 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_options_alter_genrefilmwork_film_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True,
                                            verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='last login')),
            ],
            options={
                'verbose_name': 'verbose_name_users',
                'verbose_name_plural': 'verbose_name_users_plural',
                'db_table': 'content"."users',
            },
        ),
    ]
